version: '3'
services:
 backend:
  build: ./backend
  ports:
   - "5000:5000"
  volumes:
   - ./backend:/usr/src/app
  environment:
   - ENV=development
   - PORT=5000
   - DB=mongodb+srv://bot:bot123@feature-hunt.6gqvj.mongodb.net/feature-hunt?retryWrites=true&w=majority
   #- DB=mongodb://mongodb:27017/todoDev
   

 frontend:
  build: .
  volumes:
    - ./src:/usr/src/app/src
    - ./public:/usr/src/app/public
    - ./test:/usr/src/app/test
  ports:
    - 8080:3000
  stdin_open: true


networks:
 default:
  name: feature_hunt
