#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo $(pwd)
pip freeze > ./api/requirements_check.txt
cmp --silent ./api/requirements_check.txt ./api/requirements.txt

if [ $? -gt 0 ]; 
then
  echo "There are packages in the env not in requirements.txt"
  echo "Aborting commit"
  echo "Compare the output of pip freeze with requirements.txt "
  rm ./api/requirements_check.txt
  exit 1
fi

rm ./api/requirements_check.txt
exit 0